### ISSUE TITLE
Error when preProcessing HMEC example data 

### ISSUE THREAD

**Issue by YColino** [chris-mcginnis-ucsf/MULTI-seq#22]
Hi Chris, 

I am testing the pipeline with the HMEC example data, but I get the following error: 

```
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 550, 705
```

See my code bellow:

```
cell.id<- read.table("cellIDs.txt")
cell.id.vec <- cell.id$x

## Pre-process MULTI-seq sample barcode FASTQs
readTable <- MULTIseq.preProcess(R1 = 'ACAGTG_S3_L001_R1_001.fastq.gz', R2 = 'ACAGTG_S3_L001_R2_001.fastq.gz', cellIDs = cell.id.vec, cell=c(1,16), umi=c(17,28), tag=c(1,8))
```

Am I missing something?

Thank you so much for sharing the LMOs,

Cheers,
Yolanda

**Comment by chris-mcginnis-ucsf** [comment]
Hi @YColino -- I just tried the exact code you wrote and it worked fine. I thought maybe there could be an issue because your command creating cell.id.vec produces a vector of factors (better if its characters), but I still was able to get the readTable object. 

I've seen that "differing number of rows" error before when the FASTQ files were corrupted. However, I just downloaded the files fresh and it worked fine, so maybe your local download was faulty for some reason? Have you tried re-downloading and re-installing deMULTIplex?

Also, as stated in the readme, I do not regularly check this github page so it is best to reach out directly if issues arise.
Chris

**Comment by agsanbel** [comment]
Hi @chris-mcginnis-ucsf ,

I have the same error

I have checked ACAGTG_S3_L001_R1_001.fastq  and ACAGTG_S3_L001_R2_001.fastq files and they have different amount of reads (550 and 705, respectively) and I think that is the problem. Do you know why that happen? should they (R1 and R2) have the same number of reads?

Best,

Agus
